# Generated by Django 4.1.7 on 2023-02-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafolder', models.TextField(blank=True, null=True)),
                ('modelname', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('training', models.FloatField(blank=True, null=True)),
                ('testing', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
