# Generated by Django 4.1.7 on 2023-03-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_trainer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_folder', models.FileField(upload_to='uploaded_folders/')),
            ],
        ),
    ]
