# Generated by Django 4.1.7 on 2023-03-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_uploadedfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='session_id',
            field=models.TextField(default=123123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='user',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
